### ISSUE TITLE
如何通过系统API, 数据交互到编辑器中呢

### ISSUE THREAD

**Issue by stone512** [scscms/CNPrint-VueEditor#1]
您好, 作者,
感谢您的分享!!
API数据, 如何同步到编辑器中,进行打印呢;

有webscoket 的基础知识,  有API数据交互知识, 麻烦您, 说下描述下 数据跟编辑器的交互过程, 如果有教程的话, 鄙人去学习下

**Comment by scscms** [comment]
我们当初用于购物清单中，它不适合合并数据再放回编辑器里，因为存在分页问题。
但可以与API数据合并后预览，以图片或者pdf预览。合并过程说来也简单，取到模板与取到api数据，然后循环替换（与js模板原理一样）得到合并后的xml数据直接调用接口生成预览视图。说难就是模板解析过程需要根据业务来写。没有发现教程。

**Comment by stone512** [comment]
能简单的提供下, 您的使用案例吗? 麻烦了谢谢 @scscms

**Comment by scscms** [comment]
你去项目中下载demo.rar，没有整理的。common.js看Printer对象。

**Comment by stone512** [comment]
好的, 非常感谢您
